### ISSUE TITLE
do it support zabbix version 2.2 ??

### ISSUE THREAD

**Issue by vTNT** [AlekseyChudov/zabbix-templates#1]

**Comment by vTNT** [comment]
xxx@testdata:/etc/zabbix# zabbix_get -s xxxx -k "diskstats.discovery"
{"data":[{"{#DISK_MAJOR}":"202","{#DISK_MINOR}":"0","{#DISK_NAME}":"xvda"},{"{#DISK_MAJOR}":"202","{#DISK_MINOR}":"1","{#DISK_NAME}":"xvda1"},{"{#DISK_MAJOR}":"202","{#DISK_MINOR}":"16","{#DISK_NAME}":"xvdb"},{"{#DISK_MAJOR}":"202","{#DISK_MINOR}":"17","{#DISK_NAME}":"xvdb1"}]}

i link the template to my host . but i cannot find any item

**Comment by vTNT** [comment]
i change this line <filter>{#DISK_NAME}:^(sd[a-z]+|vd[a-z]+)$</filter>  to  <filter>{#DISK_NAME}:^(sd[a-z]+|vd[a-z]+|xvd[a-z]+)$</filter>  
now it is ok

**Comment by acudovs** [comment]
Fixed. Thank you!
