### ISSUE TITLE
cciss always returns Ok

### ISSUE THREAD

**Issue by reptation** [AlekseyChudov/zabbix-templates#2]
I've downloaded the package and am testing on Ubuntu 16.04.3 with Python 2.7.12. Concerns are the following: 
1) "./cciss discovery" only returns the first logical drive even though the server has 2 and cciss_vol_status returns 2
2) The script returns 'Ok' when run as non-privileged user even though cciss_vol_status fails when you try to do that
3) The "cciss status" always returns ok as long as there is an argument given:

> $ ./cciss status sdfake
> OK

Am I missing something? 
Thanks!

**Comment by acudovs** [comment]
Please try this version 5667dba. I tested it with both cciss and hpsa drivers.
